name:                parquet-hs
version:             0.1.0.0
github:              "yigitozkavci/parquet-hs"
license:             BSD3
author:              "Yigit Ozkavci"
maintainer:          "yigitozkavci8@gmail.com"
copyright:           "2019 Yigit Ozkavci"

extra-source-files:
- README.md
- ChangeLog.md

category: Compression
synopsis: Streaming Parquet reader

description:         Please see the README on GitHub at <https://github.com/yigitozkavci/parquet-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:         src
  ghc-options:         -Wall
  dependencies:
  - pinch
  - text
  - bytestring
  - binary
  - error-util
  - mtl
  - containers
  - conduit
  - binary-conduit
  - monad-logger
  - conduit-extra
  - generic-lens
  - lens
  - safe
  - aeson
  - unordered-containers
  - lifted-async
  - serialise
  - http-conduit
  - http-client
  - http-types
  - snappy

tests:
  parquet-hs-unit:
    main: Spec.hs
    source-dirs: tests/unit
    dependencies:
    - parquet-hs
    - hspec
    - QuickCheck
    - bytestring
    - binary
  parquet-hs-integration:
    main: Spec.hs
    source-dirs: tests/integration
    dependencies:
    - parquet-hs
    - hspec
    - QuickCheck
    - bytestring
    - mtl
    - binary
    - filepath
    - process
    - aeson
    - text
    - conduit
    - monad-logger
